import { useRef, useCallback } from "react";
import { Sex, TorsoLegProportion, ArmProportion } from "@/types";
import { getArchetype } from "@/lib/archetypes";
import { formatHeight } from "@/lib/formatters";

interface AutoNameInputs {
  height: number;
  sex: Sex;
  torsoLegRatio: TorsoLegProportion;
  armLength: ArmProportion;
}

/**
 * Generates a descriptive name like "5'9 OPERATOR" or "175cm VALKYRIE"
 * based on the lifter's height and resolved archetype.
 */
export function generateAutoName(
  inputs: AutoNameInputs,
  unit: "cm" | "inches" = "inches"
): string {
  const archetype = getArchetype(inputs.torsoLegRatio, inputs.armLength, inputs.sex);
  const heightStr = formatHeight(inputs.height, unit);
  return `${heightStr} ${archetype.name}`;
}

/**
 * Hook that tracks whether a lifter's name is auto-generated or user-customized.
 *
 * Returns a function `maybeUpdateName` that should be called when inputs change.
 * It compares the current name against what the auto-name *would have been* for
 * the previous inputs. If they match, the name is auto-generated and gets updated.
 * If they don't match, the user typed a custom name and it's left alone.
 */
export function useAutoName(
  unit: "cm" | "inches" = "inches"
) {
  const prevAutoNameRef = useRef<string | null>(null);

  const maybeUpdateName = useCallback(
    (
      currentName: string,
      newInputs: AutoNameInputs,
      setName: (name: string) => void
    ) => {
      const newAutoName = generateAutoName(newInputs, unit);

      // If name matches previous auto-name OR is one of the defaults, update it
      const isAutoGenerated =
        prevAutoNameRef.current === null || // First run — always set
        currentName === prevAutoNameRef.current || // Matches previous auto-name
        currentName === "Lifter A" ||
        currentName === "Lifter B" ||
        currentName === "";

      if (isAutoGenerated) {
        setName(newAutoName);
      }

      // Always track what the auto-name would be for current inputs
      prevAutoNameRef.current = newAutoName;
    },
    [unit]
  );

  return { maybeUpdateName };
}
